name       : dfc
version    : 3.1.1
release    : 3
source     :
    - https://github.com/Rolinh/dfc/releases/download/v3.1.1/dfc-3.1.1.tar.gz : 962466e77407dd5be715a41ffc50a54fce758a78831546f03a6bb282e8692e54
license    : BSD-3-Clause
component  : system.utils
summary    : Report file system space usage information with style
description: |
    dfc displays file system space usage using graphs and colors. In some ways, it is a modernized version of df as it is able to use colors, draw graphs and export its output to different formats such as CSV or HTML.
setup      : |
    %cmake -DPREFIX=/usr -DSYSCONFDIR=/usr/share .
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
