name       : dfc
version    : 3.1.0
release    : 1
source     :
    - https://github.com/Rolinh/dfc/archive/v3.1.0.tar.gz : 0e48c3e13b2a333f9ca76706868612fa5ebc70e0c0e2a72e6949676a06f0df34
license    : BSD-3-Clause
component  : system.utils
summary    : Report file system space usage information with style
description: |
    dfc displays file system space usage using graphs and colors. In some ways, it is a modernized version of df as it is able to use colors, draw graphs and export its output to different formats such as CSV or HTML.
setup      : |
    %cmake . -DPREFIX=/usr -DSYSCONFDIR=/etc
build      : |
    %make
install    : |
    %make_install
